run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocognit
    - asciicheck
    - gofumpt
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - nakedret
    - nolintlint
    - stylecheck
    - thelper
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/kgrsutos/CW-RailsPathMetrics
  govet:
    enable:
      - shadow
  gosec:
    excludes:
      - G107 # URL provided by user input
  stylecheck:
    checks: ["all", "-ST1003"]

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-files:
    - ".*_test.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo
    - linters:
        - revive
      text: "should have comment or be unexported"

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true
