run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/kgrsutos/cw-railspathmetrics

issues:
  exclude-dirs:
    - vendor
    - .git

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true
